name: Sync Public Branch

on:
  push:
    branches:
      - public-branch   # the branch you want to mirror

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout private repo
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Mirror to public repo
        run: |
          git config user.name "Anish Giri"
          git config user.email "anishgiri163@gmail.com"

          git remote add public https://x-access-token:${{ secrets.PUBLIC_REPO_TOKEN }}@github.com/Leptons1618/Markov-Chain-Lab.git
          git push --force public public-branch:main
